database:
  type: sqlite # sqlite ou mysql

  sqlite:
    file: economy.db

  # n√£o implementado ainda..

  mysql:
    host: localhost
    port: 3306
    database: minecraft
    user: root
    password: senha
